---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    targetPort: 8000
    protocol: TCP
  selector:
    app: employee
